name: Test

runs-on:
  workflow_dispatch:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./
          with:
            detekt_version: 1.15.0